services:
  - type: web
    name: api-simulacao-web
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y software-properties-common apt-transport-https ca-certificates wget curl unzip gnupg
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
      apt-get update
      apt-get install -y google-chrome-stable
      pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PORT
        value: 5000
